[2025-06-26T05:07:45.871+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:07:41.894263+00:00 [queued]>
[2025-06-26T05:07:45.882+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:07:41.894263+00:00 [queued]>
[2025-06-26T05:07:45.882+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-06-26T05:07:45.901+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-26 05:07:41.894263+00:00
[2025-06-26T05:07:45.909+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2025-06-26T05:07:45.937+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-26T05:07:41.894263+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpmx9mg2a8']
[2025-06-26T05:07:45.941+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask s3_upload
[2025-06-26T05:07:46.049+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:07:41.894263+00:00 [running]> on host 546653f53f1d
[2025-06-26T05:07:46.177+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rhea Santhmayor' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T05:07:41.894263+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T05:07:41.894263+00:00'
[2025-06-26T05:07:48.821+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2025-06-26T05:07:48.821+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/awss3pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2025-06-26T05:07:48.835+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250626T050741, start_date=20250626T050745, end_date=20250626T050748
[2025-06-26T05:07:48.848+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task s3_upload ('NoneType' object has no attribute 'split'; 65)
[2025-06-26T05:07:48.866+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-26T05:07:48.881+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
