[2025-06-26T05:12:54.044+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:12:50.317907+00:00 [queued]>
[2025-06-26T05:12:54.052+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:12:50.317907+00:00 [queued]>
[2025-06-26T05:12:54.052+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-06-26T05:12:54.064+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-26 05:12:50.317907+00:00
[2025-06-26T05:12:54.069+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2025-06-26T05:12:54.072+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-26T05:12:50.317907+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpypqx8xo8']
[2025-06-26T05:12:54.073+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask s3_upload
[2025-06-26T05:12:54.112+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T05:12:50.317907+00:00 [running]> on host 546653f53f1d
[2025-06-26T05:12:54.173+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rhea Santhmayor' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T05:12:50.317907+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T05:12:50.317907+00:00'
[2025-06-26T05:12:54.508+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2025-06-26T05:12:54.508+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/awss3pipeline.py", line 13, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, os.path.basename(file_path))
NameError: name 'os' is not defined
[2025-06-26T05:12:54.517+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250626T051250, start_date=20250626T051254, end_date=20250626T051254
[2025-06-26T05:12:54.530+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task s3_upload (name 'os' is not defined; 86)
[2025-06-26T05:12:54.565+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-26T05:12:54.580+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
